-- MySQL Script generated by MySQL Workbench
-- Thu Oct 30 22:04:38 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(255) NOT NULL,
  `email_usuario` VARCHAR(255) NOT NULL,
  `senha_usuario` TEXT NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fornecedor` (
  `id_fornecedor` INT NOT NULL AUTO_INCREMENT,
  `nome_fornecedor` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_fornecedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fronecedor_has_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fronecedor_has_produto` (
  `id_prod_forn` INT NOT NULL,
  `fornecedor_id_fornecedor` INT NOT NULL,
  PRIMARY KEY (`id_prod_forn`, `fornecedor_id_fornecedor`),
  INDEX `fk_fronecedor_has_produto_fornecedor1_idx` (`fornecedor_id_fornecedor` ASC) VISIBLE,
  CONSTRAINT `fk_fronecedor_has_produto_fornecedor1`
    FOREIGN KEY (`fornecedor_id_fornecedor`)
    REFERENCES `mydb`.`fornecedor` (`id_fornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produto` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `descricao_produto` VARCHAR(255) NOT NULL,
  `valor_produto` DECIMAL(8,2) NOT NULL,
  `quantidade_produto` INT NOT NULL,
  `fronecedor_has_produto_id_prod_forn` INT NOT NULL,
  `fronecedor_has_produto_fornecedor_id_fornecedor` INT NOT NULL,
  PRIMARY KEY (`id_produto`, `fronecedor_has_produto_id_prod_forn`, `fronecedor_has_produto_fornecedor_id_fornecedor`),
  INDEX `fk_produto_fronecedor_has_produto1_idx` (`fronecedor_has_produto_id_prod_forn` ASC, `fronecedor_has_produto_fornecedor_id_fornecedor` ASC) VISIBLE,
  CONSTRAINT `fk_produto_fronecedor_has_produto1`
    FOREIGN KEY (`fronecedor_has_produto_id_prod_forn` , `fronecedor_has_produto_fornecedor_id_fornecedor`)
    REFERENCES `mydb`.`fronecedor_has_produto` (`id_prod_forn` , `fornecedor_id_fornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vendas` (
  `idvendas` INT NOT NULL,
  `total_venda` DECIMAL NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`idvendas`, `usuario_id_usuario`),
  INDEX `fk_vendas_usuario1_idx` (`usuario_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_vendas_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vendas_has_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vendas_has_produto` (
  `vendas_idvendas` INT NOT NULL,
  `produto_id_produto` INT NOT NULL,
  PRIMARY KEY (`vendas_idvendas`, `produto_id_produto`),
  INDEX `fk_vendas_has_produto_produto1_idx` (`produto_id_produto` ASC) VISIBLE,
  INDEX `fk_vendas_has_produto_vendas1_idx` (`vendas_idvendas` ASC) VISIBLE,
  CONSTRAINT `fk_vendas_has_produto_vendas1`
    FOREIGN KEY (`vendas_idvendas`)
    REFERENCES `mydb`.`vendas` (`idvendas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vendas_has_produto_produto1`
    FOREIGN KEY (`produto_id_produto`)
    REFERENCES `mydb`.`produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
